version: "3.8"

services:

  backend:
    image: tejswinitiwari/ipl-win-predictor-backend:latest
    container_name: ipllive_backend
    ports:
      - "8000:8000"

  frontend:
    image: tejswinitiwari/ipl-win-predictor-frontend:latest
    container_name: ipllive_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend